export const facts = [
    {
      id: '1',
      date: '384–322 до н. э.',
      title: 'Аристотель',
      image: require('./assets/aristotle.jpg'),
      description: 'Заложил основы логики и эмпирического метода, ученик Платона и учитель Александра Великого.',
    },
    {
      id: '2',
      date: '427–347 до н. э.',
      title: 'Платон',
      image: require('./assets/plato.jpg'),
      description: 'Основал Академию в Афинах, разработал учение об идеях и справедливости.',
    },
    {
      id: '3',
      date: '469–399 до н. э.',
      title: 'Сократ',
      image: require('./assets/socrates.jpg'),
      description: 'Метод Сократа основан на вопросах и диалоге. Не оставил письменных трудов.',
    },
    {
      id: '4',
      date: '1225–1274',
      title: 'Фома Аквинский',
      image: require('./assets/aquinas.jpg'),
      description: 'Соединил христианскую теологию с философией Аристотеля, основоположник схоластики.',
    },
    {
      id: '5',
      date: '354–430',
      title: 'Августин Блаженный',
      image: require('./assets/augustine.jpg'),
      description: 'Автор "Исповеди" и "О граде Божьем", влиял на средневековую мысль.',
    },
    {
      id: '6',
      date: '1724–1804',
      title: 'Иммануил Кант',
      image: require('./assets/kant.jpg'),
      description: 'Разработал "Критику чистого разума", основатель трансцендентальной философии.',
    },
    {
      id: '7',
      date: '1770–1831',
      title: 'Георг Гегель',
      image: require('./assets/hegel.jpg'),
      description: 'Создатель диалектического метода и идеализма.',
    },
    {
      id: '8',
      date: '1818–1883',
      title: 'Карл Маркс',
      image: require('./assets/marx.jpg'),
      description: 'Автор "Капитала", создатель теории исторического материализма.',
    },
    {
      id: '9',
      date: '1844–1900',
      title: 'Фридрих Ницше',
      image: require('./assets/nietzsche.jpg'),
      description: 'Автор идеи "сверхчеловека", критик морали и религии.',
    },
    {
      id: '10',
      date: '1596–1650',
      title: 'Рене Декарт',
      image: require('./assets/descartes.jpg'),
      description: 'Отец современной философии, "Мыслю, следовательно, существую".',
    },
    {
      id: '11',
      date: '1632–1704',
      title: 'Джон Локк',
      image: require('./assets/locke.jpg'),
      description: 'Развивал идею прав человека и эмпиризм.',
    },
    {
      id: '12',
      date: '1711–1776',
      title: 'Дэвид Юм',
      image: require('./assets/hume.jpg'),
      description: 'Скептик, критиковал причинность и религиозные аргументы.',
    },
    {
      id: '13',
      date: '1588–1679',
      title: 'Томас Гоббс',
      image: require('./assets/hobbes.jpg'),
      description: 'Автор "Левиафана", обосновал идею социального контракта.',
    },
    {
      id: '14',
      date: '1806–1873',
      title: 'Джон Стюарт Милль',
      image: require('./assets/mill.jpg'),
      description: 'Приверженец утилитаризма и свободомыслия.',
    },
    {
      id: '15',
      date: '1878–1958',
      title: 'Карл Ясперс',
      image: require('./assets/jaspers.jpg'),
      description: 'Экзистенциалист, исследовал свободу и трансценденцию.',
    },
    {
      id: '16',
      date: '1889–1976',
      title: 'Мартин Хайдеггер',
      image: require('./assets/heidegger.jpg'),
      description: 'Автор "Бытие и время", исследовал бытие как таковое.',
    },
    {
      id: '17',
      date: '1908–1961',
      title: 'Морис Мерло-Понти',
      image: require('./assets/merleau.jpg'),
      description: 'Развивал феноменологию восприятия.',
    },
    {
      id: '18',
      date: '1905–1980',
      title: 'Жан-Поль Сартр',
      image: require('./assets/sartre.jpg'),
      description: 'Экзистенциалист, автор "Тошноты" и "Бытия и ничто".',
    },
    {
      id: '19',
      date: '1926–1984',
      title: 'Мишель Фуко',
      image: require('./assets/foucault.jpg'),
      description: 'Анализировал власть, дисциплину и социальные институты.',
    },
    {
      id: '20',
      date: '1859–1938',
      title: 'Эдмунд Гуссерль',
      image: require('./assets/husserl.jpg'),
      description: 'Основатель феноменологии, вводит понятие интенциональности.',
    },
    {
      id: '21',
      date: '1859–1952',
      title: 'Бернард Рассел',
      image: require('./assets/russell.jpg'),
      description: 'Развивал аналитическую философию и логику.',
    },
    {
      id: '22',
      date: '1889–1951',
      title: 'Людвиг Витгенштейн',
      image: require('./assets/wittgenstein.jpg'),
      description: 'Исследовал язык и его границы в "Логико-философском трактате".',
    },
    {
      id: '23',
      date: '1712–1778',
      title: 'Жан-Жак Руссо',
      image: require('./assets/rousseau.jpg'),
      description: 'Предложил концепцию "естественного человека", развивал идею народного суверенитета.',
    },
    {
      id: '24',
      date: '1748–1832',
      title: 'Джереми Бентам',
      image: require('./assets/bentham.jpg'),
      description: 'Основоположник утилитаризма.',
    },
    {
      id: '25',
      date: '1856–1939',
      title: 'Зигмунд Фрейд',
      image: require('./assets/freud.jpg'),
      description: 'Создал психоанализ, оказал влияние на философию культуры.',
    },
    {
      id: '26',
      date: '1903–1969',
      title: 'Теодор Адорно',
      image: require('./assets/adorno.jpg'),
      description: 'Представитель Франкфуртской школы, критиковал массовую культуру.',
    },
    {
      id: '27',
      date: '1929–2004',
      title: 'Жак Деррида',
      image: require('./assets/derrida.jpg'),
      description: 'Основатель деконструкции, критиковал структуру языка.',
    },
    {
      id: '28',
      date: '1883–1950',
      title: 'Карл Поппер',
      image: require('./assets/popper.jpg'),
      description: 'Разработал принцип фальсифицируемости научных теорий.',
    },
    {
      id: '29',
      date: '1919–2002',
      title: 'Ганс Гадамер',
      image: require('./assets/gadamer.jpg'),
      description: 'Развивал философскую герменевтику.',
    },
    {
      id: '30',
      date: '1926–1998',
      title: 'Ханс-Йонас',
      image: require('./assets/jonas.jpg'),
      description: 'Этик экологии, сформулировал "принцип ответственности".',
    },
  ];
  